      COMMON /VAR/ DENSIT,VISCOS,FLOMAS,FMOUT,FAC,
     &             U(NXYZ),V(NXYZ),P(NXYZ),PP(NXYZ),W(NXYZ),
     &             F1(NXYZ),F2(NXYZ),F3(NXYZ),
     &             DPX(NXYZ),DPY(NXYZ),DPZ(NXYZ),
     &             DUX(NXYZ),DUY(NXYZ),DUZ(NXYZ),
     &             DVX(NXYZ),DVY(NXYZ),DVZ(NXYZ),
     &             DWX(NXYZ),DWY(NXYZ),DWZ(NXYZ),
     &             VOL(NXYZ),SHR(NXYZ),WTE(NXYZ),
     &             BDY1(NXYZ),BDY2(NXYZ),BDY3(NXYZ)
      DOUBLE PRECISION DENSIT,VISCOS,FLOMAS,FMOUT,FAC,
     &                 U,V,P,PP,W,F1,F2,F3,DPX,DPY,DPZ,BDY1,BDY2,BDY3,
     &                 DUX,DUY,DUZ,DVX,DVY,DVZ,DWX,DWY,DWZ,VOL,SHR,WTE
